default = {}

dofile("blocks.lua")
dofile("items.lua")
dofile("tree.lua")
dofile("mapgen.lua")
dofile("lab_dungeon.lua")
dofile("ai_holo.lua")
dofile("melee_swing.lua")
dofile("projectiles.lua")
dofile("tools.lua")
dofile("weapons.lua")
dofile("equipment.lua")
dofile("player.lua")
dofile("crafting.lua")
dofile("effects.lua")
